#!/usr/bin/env bash
# Default ship deploy stub.
#
# Drop-in placeholder generated by `ship` when bootstrapping a new
# project. Replace the body with your real deploy (build, push, swap
# container, run healthcheck, etc.). All this stub does is send a
# notification so you can see the loop fire end-to-end.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

short_sha="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
"${SCRIPT_DIR}/notify.sh" "🚢 ship deploy stub: would deploy ${short_sha}" || true
echo "ship deploy stub: nothing to do (edit .ship/deploy.sh to actually ship)"
