name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: grep '^export ' .envrc | sed -e 's/^export //' -e 's/="\(.*\)"/=\1/' >> "$GITHUB_ENV"
      - run: ./scripts/build.sh linux/amd64
      - run: ./test/e2e.sh
        env:
          SKIP_DOCKER_BUILD: 1
